# Generated by Django 5.2.10 on 2026-07-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_camisa_descripcion_chaleco_descripcion_and_more'),
        ('core', '0002_alter_configuracionsitio_instagram_url_and_more'),
        ('prendas', '0007_alter_prenda_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVisitas',
            fields=[
            ],
            options={
                'verbose_name': 'Direccion de visitas',
                'verbose_name_plural': 'Direccion de visitas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.configuracionsitio',),
        ),
        migrations.AddField(
            model_name='traje',
            name='color_stock',
            field=models.ForeignKey(blank=True, help_text='Color maestro usado para mostrar talles existentes en Stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_catalogo', to='prendas.color'),
        ),
    ]
