# Generated by Django 5.2.10 on 2026-07-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_traje_talles_stock_cache'),
        ('prendas', '0009_normalize_chaleco_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='camisa',
            name='colores_stock',
            field=models.ManyToManyField(blank=True, help_text='Se muestran solamente colores que existen en Stock para esta categoría.', related_name='%(class)s_catalogo', to='prendas.color', verbose_name='Colores disponibles'),
        ),
        migrations.AddField(
            model_name='chaleco',
            name='colores_stock',
            field=models.ManyToManyField(blank=True, help_text='Se muestran solamente colores que existen en Stock para esta categoría.', related_name='%(class)s_catalogo', to='prendas.color', verbose_name='Colores disponibles'),
        ),
        migrations.AddField(
            model_name='cinturon',
            name='colores_stock',
            field=models.ManyToManyField(blank=True, help_text='Se muestran solamente colores que existen en Stock para esta categoría.', related_name='%(class)s_catalogo', to='prendas.color', verbose_name='Colores disponibles'),
        ),
        migrations.AddField(
            model_name='combo',
            name='disponible_todos_trajes',
            field=models.BooleanField(default=True, help_text='Incluye automáticamente los trajes publicados actuales y futuros.', verbose_name='Disponible para todos los trajes activos'),
        ),
        migrations.AddField(
            model_name='corbata',
            name='colores_stock',
            field=models.ManyToManyField(blank=True, help_text='Se muestran solamente colores que existen en Stock para esta categoría.', related_name='%(class)s_catalogo', to='prendas.color', verbose_name='Colores disponibles'),
        ),
        migrations.AddField(
            model_name='traje',
            name='colores_stock',
            field=models.ManyToManyField(blank=True, help_text='Se muestran solamente colores que existen en Stock para esta categoría.', related_name='%(class)s_catalogo', to='prendas.color', verbose_name='Colores disponibles'),
        ),
        migrations.AddField(
            model_name='zapato',
            name='colores_stock',
            field=models.ManyToManyField(blank=True, help_text='Se muestran solamente colores que existen en Stock para esta categoría.', related_name='%(class)s_catalogo', to='prendas.color', verbose_name='Colores disponibles'),
        ),
    ]
