# Generated by Django 5.2.10 on 2026-01-23 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=80)),
                ('cliente_telefono', models.CharField(max_length=30)),
                ('fecha_visita', models.DateField()),
                ('fecha_reserva', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('persona1_nombre', models.CharField(max_length=80)),
                ('persona2_nombre', models.CharField(blank=True, default='', max_length=80)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sena', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_saldo', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=12)),
                ('estado_alquiler', models.CharField(choices=[('RESERVADO', 'Reservado'), ('ENTREGADO', 'Entregado'), ('CERRADO', 'Cerrado')], default='RESERVADO', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlquilerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_num', models.PositiveSmallIntegerField(default=1)),
                ('ruedo_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ruedo_tipo', models.CharField(blank=True, choices=[('CM', 'cm'), ('BOTON', 'botón')], default='', max_length=10)),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='alquileres.alquiler')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prendas.prenda')),
            ],
        ),
    ]
