# Generated by Django 6.0.1 on 2026-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('prenda', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('talle', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('celular_cliente', models.CharField(max_length=20)),
                ('ruedo_pantalon', models.CharField(blank=True, max_length=50, null=True)),
                ('ruedo_saco', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_visita', models.DateField()),
                ('fecha_retiro', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('total_a_abonar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seña', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago_sena', models.CharField(max_length=20)),
                ('saldo_restante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago_saldo', models.CharField(max_length=20)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('prendas', models.ManyToManyField(related_name='alquileres', to='alquileres.traje')),
            ],
        ),
    ]
