# Generated by Django 5.2.10 on 2026-02-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='metodo_saldo',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='metodo_sena',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='saldo_pagado_en',
            field=models.DateField(blank=True, null=True),
        ),
    ]
