# Generated by Django 6.0.1 on 2026-01-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
