# Generated by Django 6.0.1 on 2026-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0002_alquiler_metodo_saldo_alquiler_metodo_sena_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alquiler',
            index=models.Index(fields=['fecha_reserva'], name='alquileres__fecha_r_de728e_idx'),
        ),
        migrations.AddIndex(
            model_name='alquiler',
            index=models.Index(fields=['fecha_entrega'], name='alquileres__fecha_e_cdbafc_idx'),
        ),
        migrations.AddIndex(
            model_name='alquiler',
            index=models.Index(fields=['fecha_devolucion'], name='alquileres__fecha_d_fb386c_idx'),
        ),
        migrations.AddIndex(
            model_name='alquiler',
            index=models.Index(fields=['estado_alquiler', 'fecha_entrega'], name='alquileres__estado__c66db7_idx'),
        ),
        migrations.AddIndex(
            model_name='alquiler',
            index=models.Index(fields=['estado_alquiler', 'fecha_devolucion'], name='alquileres__estado__60920f_idx'),
        ),
        migrations.AddIndex(
            model_name='alquiler',
            index=models.Index(fields=['estado_saldo', 'saldo_pagado_en'], name='alquileres__estado__c304cc_idx'),
        ),
    ]
