# Generated by Django 5.2.10 on 2026-07-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0003_alquiler_alquileres__fecha_r_de728e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='persona3_nombre',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='persona4_nombre',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='persona5_nombre',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='persona6_nombre',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
