# Generated by Django 5.2.10 on 2026-07-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0004_alquiler_persona3_nombre_alquiler_persona4_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado_alquiler',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('ENTREGADO', 'Entregado'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=12),
        ),
    ]
