# Generated by Django 5.2.10 on 2026-07-23 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0007_cliente_alquiler_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='credito_cancelacion_generado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='saldo_a_favor_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='alquileritem',
            name='ruedo_listo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquileritem',
            name='ruedo_listo_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alquileritem',
            name='ruedo_listo_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruedos_marcados_listos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_a_favor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
