# Generated by Django 5.2.10 on 2026-02-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(help_text='Ej: +54 9 221 ...', max_length=40)),
                ('fecha_evento', models.DateField()),
                ('inicio', models.DateTimeField(help_text='Fecha y hora de la visita')),
                ('duracion_min', models.PositiveSmallIntegerField(choices=[(30, '30 min'), (60, '60 min')], default=30)),
                ('personas', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
    ]
