# Generated by Django 5.2.10 on 2026-07-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0008_alquiler_credito_cancelacion_generado_and_more'),
        ('catalogo', '0006_configuracionvisitas_traje_color_stock'),
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloqueo de agenda',
                'verbose_name_plural': 'Bloqueos de agenda',
                'ordering': ['fecha', 'hora_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaAmboVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('linea', models.CharField(blank=True, default='', max_length=20)),
                ('tela', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('talle_saco', models.CharField(max_length=50)),
                ('talle_pantalon', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Preferencia de ambo',
                'verbose_name_plural': 'Preferencias de ambos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-fecha_visita', '-hora_visita', '-created_at']},
        ),
        migrations.AddField(
            model_name='visita',
            name='alquiler',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visita_origen', to='alquileres.alquiler'),
        ),
        migrations.AddField(
            model_name='visita',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visita',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='alquileres.cliente'),
        ),
        migrations.AddField(
            model_name='visita',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha_visita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='hora_visita',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='observaciones_internas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visita',
            name='origen',
            field=models.CharField(choices=[('WEB', 'Web'), ('MANUAL', 'Manual')], default='WEB', max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='vio_prendas_catalogo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vio prendas en el catalogo'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada'), ('NO_ASISTIO', 'No asistio')], default='CONFIRMADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['fecha_visita', 'hora_visita'], name='visitas_fecha_hora_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['fecha_visita', 'estado'], name='visitas_fecha_estado_idx'),
        ),
        migrations.AddField(
            model_name='preferenciaambovisita',
            name='traje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferencias_visita', to='catalogo.traje'),
        ),
        migrations.AddField(
            model_name='preferenciaambovisita',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_ambos', to='visitas.visita'),
        ),
    ]
