# Generated by Django 5.2.10 on 2026-07-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_preservar_visitas_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciaambovisita',
            name='producto_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferenciaambovisita',
            name='producto_nombre',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='preferenciaambovisita',
            name='producto_tipo',
            field=models.CharField(blank=True, default='traje', max_length=30),
        ),
        migrations.AlterField(
            model_name='preferenciaambovisita',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='preferenciaambovisita',
            name='talle_pantalon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='preferenciaambovisita',
            name='talle_saco',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
