# Generated by Django 5.2.10 on 2026-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_perfilusuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('ADMINISTRADOR', 'Administrador'), ('EMPLEADO', 'Empleado'), ('COSTURERA', 'Costurera')], default='EMPLEADO', max_length=20),
        ),
    ]
