# Generated by Django 5.2.10 on 2026-01-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True)),
                ('categoria', models.CharField(choices=[('SACO', 'Saco'), ('PANTALON', 'Pantalón'), ('CAMISA', 'Camisa'), ('CHALECO', 'Chaleco'), ('MONO', 'Moño'), ('CORBATA', 'Corbata'), ('ZAPATOS', 'Zapatos'), ('CINTURON', 'Cinturón')], max_length=20)),
                ('marca', models.CharField(blank=True, default='', max_length=40)),
                ('color', models.CharField(blank=True, default='', max_length=40)),
                ('talle', models.CharField(blank=True, default='', max_length=20)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('ENTREGADO', 'Entregado'), ('DANADA', 'Dañada')], default='DISPONIBLE', max_length=20)),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
