# Generated by Django 6.0.1 on 2026-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0002_prenda_origen'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prenda',
            index=models.Index(fields=['categoria', 'estado'], name='prendas_pre_categor_0307d1_idx'),
        ),
        migrations.AddIndex(
            model_name='prenda',
            index=models.Index(fields=['origen'], name='prendas_pre_origen_d2cc16_idx'),
        ),
        migrations.AddIndex(
            model_name='prenda',
            index=models.Index(fields=['marca'], name='prendas_pre_marca_24d3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='prenda',
            index=models.Index(fields=['color'], name='prendas_pre_color_eabd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='prenda',
            index=models.Index(fields=['talle'], name='prendas_pre_talle_9a9920_idx'),
        ),
    ]
