# Generated by Django 5.2.10 on 2026-01-26 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('para_tade', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('para_bauti', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.CharField(blank=True, default='', max_length=140)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
