# Generated by Django 5.2.10 on 2026-01-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_informaciongeneral'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformacionGeneral',
            new_name='DivisionBienes',
        ),
    ]
