# Generated by Django 5.2.10 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0003_rename_informaciongeneral_divisionbienes"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="notas",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
