# Generated by Django 5.2.10 on 2026-07-23 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0008_alquiler_credito_cancelacion_generado_and_more'),
        ('gastos', '0004_gasto_notas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('fecha_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('concepto', models.CharField(max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=160)),
                ('ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('egreso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('informativo', models.BooleanField(db_index=True, default=False)),
                ('alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alquileres.alquiler')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alquileres.cliente')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.divisionbienes')),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.gasto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
    ]
